project:
  type: website
  title: "B3D Workshop, Uni Köln 2023, Cologne"
website:
  title: "B3D Workshop"
  favicon: images/b3d.png  

  #site-url: https://crsl4.github.io/julia-workshop
  #repo-url: https://github.com/crsl4/julia-workshop
  navbar:
    logo: images/b3d.png
    href: https://b3d.nrw/
    right:
        - text: Home
          href: index.qmd
        - text: Program
          href: program.qmd
        - text: Participants
          href: Participants.qmd
        - text: Logistics
          href: Logistics.qmd
        - text: Registration
          href: registration.qmd
format:
  html:
    theme: [sandstone, custom.scss]
    css: styles.css
    toc: true
    toc-title: Contents
    toc-location: left

#jupyter: julia-1.8
